#
# This workflow will build and run all unit tests.
#

name: DevHome-CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature*" ]

permissions:
  contents: read

jobs:
  dotnet-build-and-test:
    strategy:
        matrix:
          os: [windows-latest]
          configuration: [Release, Debug]
          platform: [x64, x86, arm64]
          dotnet-version: ['6.0.x']
    runs-on: ${{ matrix.os }}
    env:
      MSIX_VERSION: "0.1"
      SDK_VERSION: "0.1"
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true

    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '17.5'

    # - name: Restore DevHomeSDK NuGet packages
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   run: nuget restore pluginsdk\DevHomeSDK.sln

    # - name: Build_DevHomeSDK
    #   shell: pwsh
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   run: .\Build.ps1 -Configuration "Release" -SDKVersion ${{env.SDK_VERSION}} -BuildStep "sdk"

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Restore DevHome NuGet packages
      run: |
        nuget restore pluginsdk\DevHomeSDK.sln
        nuget restore DevHome.sln

    - name: Build_DevHome
      shell: pwsh
      run: .\Build.ps1 -Platform ${{ matrix.platform }} -Configuration ${{ matrix.configuration }}

    - name: Run Unittests
      shell: pwsh
      run: .\Test.ps1 -Platform ${{ matrix.platform }} -Configuration ${{ matrix.configuration }}

    # - name: Upload dotnet test results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dotnet-testresults-${{ matrix.configuration }}
    #     path: ./TestResults
    #   if: ${{ always() }}
