#
# This workflow will build and run all unit tests.
#

name: DevHome-CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature*" ]

permissions:
  contents: read

jobs:
  dotnet-build-and-test:
    strategy:
        matrix:
          os: [windows-latest]
          configuration: [Release, Debug]
          platform: [x64, x86, arm64]
          dotnet-version: ['6.0.x']
    runs-on: ${{ matrix.os }}
    env:
      MSIX_VERSION: "0.1"
      SDK_VERSION: "0.1"
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true

    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '17.5'

    - name: Download nuget
      run: |
        mkdir ".\.nuget"
        Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile ".\.nuget\nuget.exe"

    - name: Find VsDevCmd.bat
      run: |
        $VSDevCmd = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere" -latest -find Common7\tools\VSDevCmd.bat
        if (!$VSDevCmd) { exit 1 }
        echo "Using VSDevCmd: ${VSDevCmd}"
        Add-Content $env:GITHUB_ENV "VSDevCmd=$VSDevCmd"

    - name: Restore dependencies
      shell: bash
      run: |
        dotnet restore DevHome.sln -p:PublishReadyToRun=true

    - name: Build_SDK
      run: cmd /c "$env:VSDevCmd" "&" msbuild /m /p:Configuration=Release,Platform=${{ matrix.platform }} pluginsdk\\DevHomeSDK.sln

    - name: Build_DevHome
      run: cmd /c "$env:VSDevCmd" "&" msbuild /m /p:Configuration=${{ matrix.configuration }},Platform=${{ matrix.platform }} DevHome.sln

    - name: Find vstest.console.exe
      run: |
        $VSDevTestCmd = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere" -latest -prerelease -products * -find **\TestPlatform\vstest.console.exe
        if (!$VSDevTestCmd) { exit 1 }
        echo "Using VSDevTestCmd: ${VSDevTestCmd}"
        Add-Content $env:GITHUB_ENV "VSDevTestCmd=$VSDevTestCmd"

    - name: DevHome Unittests
      run: cmd /c "$env:VSDevTestCmd" /Platform:${{ matrix.platform }} /Logger:trx;LogFileName=DevHome.Test-${{ matrix.platform }}-${{ matrix.configuration }}.trx test\bin\${{ matrix.platform }}\${{ matrix.configuration }}\net6.0-windows10.0.22000.0\DevHome.Test.dll

    # - name: Run Unittests
    #   shell: pwsh
    #   run: .\Test.ps1 -Platform ${{ matrix.platform }} -Configuration ${{ matrix.configuration }}

    # - name: Upload dotnet test results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dotnet-testresults-${{ matrix.configuration }}
    #     path: ./TestResults
    #   if: ${{ always() }}
